config/urls.py
from django.contrib import admin
from django.urls import include, path
from cooler_math_games.views import home_redirect_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('games/', include('cooler_math_games.urls')),
    path('', home_redirect_view, name='default'),
]

cooler_math_games/urls.py
from django.urls import path, include

from . import views

app_name = 'cooler_math_games'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('Mines/', views.mines, name='Mines'),
    path('Catcher/', views.catcher, name='Catcher'),
    path('Tomato/', views.tomato, name='Tomato'),
    path('2048/', views.game_2048, name='2048'),
    path('2048Fibonacci/', views.game_2048_Fibonacci, name='2048Fibonacci'),
    path('Sudoku/', views.sudoku, name='Sudoku'),
    path('Climber/', views.climber, name='Climber'),
    path('Hangman/', views.hangman, name='Hangman'),
    path('PhaserTest/', views.phaser_test, name='PhaserTest'),
    path('credits/', views.credits, name='Credits'),
    path('game_end/<int:score>/<str:game_name>/', views.game_end, name='game_end'),
    path('leaderboards/<str:games_or_user>/', views.leaderboards, name='leaderboards')
]

cooler_math_games/models.py
from django.db import models


class Game(models.Model):
    name = models.CharField(max_length=20)
    author = models.CharField(max_length=20)
    total_plays = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.name} by {self.author} currently has {self.total_plays} total plays'


class GameScore(models.Model):
    user = models.CharField(max_length=20)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    date_obtained = models.DateField()

    def __str__(self):
        return f'{self.user} obtained a score of {self.score} in {self.game.name} on {self.date_obtained}'

cooler_math_games/forms.py
from django import forms


class SaveScoreForm(forms.Form):
    """
    Form to save users scores after playing games
    """
    user = forms.CharField(max_length=20, disabled=True)
    score = forms.IntegerField(disabled=True)
    game = forms.CharField(max_length=30, disabled=True)

cooler_math_games/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.utils.timezone import now
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView

from .models import Game, GameScore
from .forms import SaveScoreForm


class SignUp(CreateView):
    """
    View class to allow users to sign up for an account to track their scores
    """
    form_class = UserCreationForm
    success_url = reverse_lazy('cooler_math_games:login')
    template_name = 'registration/signup.html'


def home_redirect_view(request):
    """
    Redirect the default page to the home cooler math games view
    """
    return HttpResponseRedirect('/games/home/')


def home(request):
    """
    The home page for cooler math games
    """
    all_games = Game.objects.order_by('-total_plays')  # get all games in descending order of plays
    game_urls = []
    for game in all_games:
        game_urls.append(
            f'http://127.0.0.1:8000/games/{game.name}/')  # todo if we ever run this on a real server we will need to change the url a bit
    return render(request, 'cooler_math_games/home.html', {'top_games': all_games, 'game_urls': game_urls})


def game_end(request, score, game_name):
    """
    score saving page for cooler math games
    :param request: http request
    :param score: The score of the game played
    :param game_name: The name of the game played
    """
    if request.method == 'POST':  # if the form is submitted save the score to the db and go home
        form = SaveScoreForm(request.POST)
        print(form.data)
        game = Game.objects.get(name=game_name)
        if request.user.is_authenticated:
            user = request.user.username
        else:
            user = 'guest'
        GameScore.objects.create(user=user, game=game, score=score, date_obtained=now())
        return HttpResponseRedirect(f'/games/leaderboards/{game}')
    else:  # fill out form with game score data
        form = SaveScoreForm()
        if request.user.is_authenticated:
            form.fields['user'].initial = request.user.username
        else:
            form.fields['user'].initial = 'guest'
        form.fields['score'].initial = score
        form.fields['game'].initial = game_name
    return render(request, 'cooler_math_games/game_end.html', {'form': form, 'game': game_name, 'score': score})


def leaderboards(request, games_or_user):
    """
    Leaderboard view for coolermath games
    :param request: http request
    :param games_or_user: name of game, if you want all games just make this "all", if you want all games for the current user input current_user
    """
    if games_or_user in ('all', 'current_user'):
        games = Game.objects.all()
    else:
        # only get data on games requested
        games_requested = games_or_user.split(' ')
        games = Game.objects.filter(name__in=games_requested)

    # get data on the top 10 scores for each applicable game, or get all scores for a specific user
    leader_boards = {}
    for game in games:
        if games_or_user == 'current_user':
            if request.user.is_authenticated:
                scores_for_game = GameScore.objects.filter(game=game).filter(user=request.user.username).order_by('-score')
            else:
                scores_for_game = GameScore.objects.filter(game=game).filter(user='guest').order_by('-score')
        elif games_or_user == 'all':
            scores_for_game = GameScore.objects.filter(game=game).order_by('-score')[:10] # only get top 10 scores for each game
        else:
            scores_for_game = GameScore.objects.filter(game=game).order_by('-score')

        formatted_game_scores = []
        for game_score in scores_for_game:
            formatted_game_scores.append({'score': game_score.score, 'user': game_score.user, 'time': game_score.date_obtained})
        leader_boards[game.name] = formatted_game_scores
    return render(request, 'cooler_math_games/leaderboards.html', {'leader_boards': leader_boards})


# PUT GAME VIEWS BELOW HERE
def mines(request):
    """
    The minesweeper game view
    """
    mines_game_db = Game.objects.get(name='mines')
    mines_game_db.total_plays += 1
    mines_game_db.save()
    return render(request, 'cooler_math_games/mines.html')


def catcher(request):
    """
    The Catcher game view
    """
    catcher_game_db = Game.objects.get(name='catcher')
    catcher_game_db.total_plays += 1
    catcher_game_db.save()
    return render(request, 'cooler_math_games/catcher.html')


def game_2048(request):
    """
    The 2048 game view
    """
    game_2048_db = Game.objects.get(name='2048')
    game_2048_db.total_plays += 1
    game_2048_db.save()
    return render(request, 'cooler_math_games/2048.html')

def game_2048_Fibonacci(request):
    """
    The 2048 Fib game view
    """
    game_2048_fibonacci_db = Game.objects.get(name='2048Fibonacci')
    game_2048_fibonacci_db.total_plays += 1
    game_2048_fibonacci_db.save()
    return render(request, 'cooler_math_games/2048Fibonacci.html')

def climber(request):
    """
    The climber game view
    """
    climber_db = Game.objects.get(name='climber')
    climber_db.total_plays += 1
    climber_db.save()
    return render(request, 'cooler_math_games/climber.html')

def phaser_test(request):
    """
    The test phaser game view
    """
    phaser_game_db = Game.objects.get(name='phasertest')
    phaser_game_db.total_plays += 1
    phaser_game_db.save()
    return render(request, 'cooler_math_games/phaser_test.html')


def tomato(request):
    """
    The Tomato Dash game view
    """
    # todo right now the user is always anon, will be changed in the future
    tomato_game_db = Game.objects.get(name='tomato')
    tomato_game_db.total_plays += 1
    tomato_game_db.save()
    return render(request, 'cooler_math_games/tomato.html')


def hangman(request):
    """
    The hangman game view
    """
    hangman_db = Game.objects.get(name='hangman')
    hangman_db.total_plays += 1
    hangman_db.save()
    return render(request, 'cooler_math_games/hangman.html')

def sudoku(request):
    """
    The sudoku game view
    """
    sudoku_db = Game.objects.get(name='sudoku')
    sudoku_db.total_plays += 1
    sudoku_db.save()
    return render(request, 'cooler_math_games/sudoku.html')

def credits(request):
    """
    The credits view
    """
    return render(request, 'cooler_math_games/credits.html')

cooler_math_games/templates/cooler_math_games/2048.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale:1.0">
        <title>2048</title>

        {% load static %}
        <link href="{% static 'cooler_math_games/2048/2048.css' %}" rel="stylesheet">
        <script src ="{% static 'cooler_math_games/2048/2048.js' %}" type="text/javascript"></script>
    </head>

    {% include "./header.html" %}

    <br>

    <body id="number-page">
        <h1>2048</h1>
        <hr>
        <h2>Score: <span id="score">0</span></h2>
        <div id="board">
        </div>
        <button onclick="quit_game()" class="button-link">Quit Game</button>
    </body>
</html>

cooler_math_games/templates/cooler_math_games/2048Fibonacci.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale:1.0">
        <title>2048</title>

        {% load static %}
        <link href="{% static 'cooler_math_games/2048Fibonacci/2048Fibonacci.css' %}" rel="stylesheet">
        <script src ="{% static 'cooler_math_games/2048Fibonacci/2048Fibonacci.js' %}" type="text/javascript"></script>
    </head>

    {% include "./header.html" %}

    <br>

    <body id="number-page">
        <h1>2048 Fibonacci</h1>
        <hr>
        <h2>Score: <span id="score">0</span></h2>
        <div id="board">
        </div>
        <button onclick="quit_game()" class="button-link">Quit Game</button>
    </body>
</html>

cooler_math_games/templates/cooler_math_games/catcher.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Bug Catcher!</title>
    {% load static %}
    <link href="{% static 'cooler_math_games/page.css' %}" rel="stylesheet">
    <link href="{% static 'cooler_math_games/catcher/catcher.css' %}" rel="stylesheet">
</head>

{% include "./header.html" %}

<body>
    <div id="instructions">
    <h2>Instructions</h2>
    <p>
        Catch as many bugs as you can in 15 seconds! Use the left and right arrow keys to move! Good luck!
    </p>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/phaser@3.16.2/dist/phaser.min.js"></script>
    <script src="{% static 'cooler_math_games/catcher/catcher.js' %}" type="text/javascript"></script>
</body>
</html>

cooler_math_games/templates/cooler_math_games/climber.html
<!doctype html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8" />
    <title>climber</title>
    <script src="//cdn.jsdelivr.net/npm/phaser@3.11.0/dist/phaser.js"></script>
    {% load cooler_math_games_extras %}
    {% load static %}\
    <link href="{% static 'cooler_math_games/climber/climber.css' %}" rel="stylesheet">
    <link href="{% static 'cooler_math_games/page.css' %}" rel="stylesheet">
</head>

{% include "./header.html" %}
<br>

<body>
    <script src="{% static 'cooler_math_games/climber/climber.js' %}" type="text/javascript"></script>
</body>
</html>

cooler_math_games/templates/cooler_math_games/credits.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Credits</title>

        {% load static %}
        <link href="{% static 'cooler_math_games/credits/credits.css' %}" rel="stylesheet">
        <script src ="{% static 'cooler_math_games/credits/credits.js' %}" type="text/javascript"></script>
    </head>

    <body>
        <div id="cards">
            <div class="card">
                <div class="text-container">
                    <h2><b>About our Team</b></h2>
                        <p>Hello! Welcome to CoolerMathGames, a project designed and developed by a team of students for their senior design project course, CS498. We would like to acknowledge all of the hard work and dedication of each team member who contributed to this project's success. Thanks for visiting CoolerMathGames, and we hope you enjoy our website!</p>
                </div>
            </div>

            <div class="card">
                <div class="image-container">
                    <img src="{% static 'cooler_math_games/images/Cole.png' %}" alt="Cole Thacker" id="cole-pic" class="image">
                    <h4><b>Cole Thacker: &emsp;Web Development</b></h4>
                </div>
                <div class="text-container">
                    <p>Cole is a senior who enjoys coding and loves to learn new technologies. After graduation, Cole plans to work as a software developer to have the chance to continue learning and growing.</p>
                </div>
            </div>
            
            <div class="card">
                <div class="image-container">
                    <img src="{% static 'cooler_math_games/images/Tony.png' %}" alt="Tony Li" id="tony-pic" class="image">
                    <h4><b>Tony Li: &emsp;&emsp;&emsp;&emsp;Web Development</b></h4>
                </div>
                <div class="text-container">
                    <p>Tony didn't give Zach a bio in time :(</p>
                </div>
            </div>

            <div class="card">
                <div class="image-container">
                    <img src="{% static 'cooler_math_games/images/Jesse.png' %}" alt="Jesse Perkins" id="jesse-pic" class="image">
                    <h4><b>Jesse Perkins: Game Development</b></h4>
                </div>
                <div class="text-container"> 
                    <p>Jesse is a senior computer science student interested in development and embedded systems. He would like to continue to building his skills as a developer and build innovative tech.</p>
                </div>
            </div>

            <div class="card">
                <div class="image-container">
                    <img src="{% static 'cooler_math_games/images/Khumbo.png' %}" alt="Khumbo Phiri" id="khumbo-pic" class="image">
                    <h4><b>Khumbo Phiri: Game Development</b></h4>
                </div>
                <div class="text-container">
                    <p>Khumbo is a senior computer science student interested in software development. Khumbo has a goal to work as a software developer after graduation and grow his skills.</p>
                </div>
            </div>

            <div class="card">
                <div class="image-container">
                    <img src="{% static 'cooler_math_games/images/Zach.png' %}" alt="Zach Snow" id="zach-pic" class="image">
                    <h4><b>Zach Snow: &emsp;Game Development</b></h4>
                </div>
                <div class="text-container">
                    <p>Zach is a senior with an interest in machine learning and data science. After graduation, he plans on working in industry before pursuing his master's degree in data science.</p>
                </div>
            </div>
        </div>
    </body>
</html>

cooler_math_games/templates/cooler_math_games/game_end.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Game Over</title>
    <link href="{% static 'cooler_math_games/game_end.css' %}" rel="stylesheet">
</head>

{% include "./header.html" %}

<body>
    <div class="container">
        <div class="game-over">
            <h2>Game Over!</h2>
        </div>
        <form action="{% url 'cooler_math_games:game_end' score game %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Save Your Score!">
            <a href="{% url 'cooler_math_games:home' %}" id="dont_save">Don't Save My Score</a>
        </form>
    </div>
</body>
</html>

cooler_math_games/templates/cooler_math_games/hangman.html
<!doctype html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8" />
    <title>Making your first Phaser 3 Game - Part 10</title>
    {% load static %}
    <link href="{% static 'cooler_math_games/page.css' %}" rel="stylesheet">
    <link href="{% static 'cooler_math_games/hangman/hangman.css' %}" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/npm/phaser@3.11.0/dist/phaser.js"></script>

</head>

{% include "./header.html" %}
<br>

<body>

<script src="{% static 'cooler_math_games/hangman/hangman.js' %}" type="text/javascript"></script>


</body>
</html>

cooler_math_games/templates/cooler_math_games/header.html
{% load cooler_math_games_extras %}
{% load static %}
<link href="{% static 'cooler_math_games/home/home.css' %}" rel="stylesheet">

<div class="header" id="home-header">
    <br>
    <img src="{% static 'cooler_math_games/images/CMG.png' %}" alt="Cooler Math Games Logo" id="logo">
</div>

<nav class="navbar" id="home-nav">
    <div id="login-menu">
        {% if user.is_authenticated %}
        <a id="logout" href="{% url 'cooler_math_games:logout' %}">&emsp;Log out {{ user.username }}!</a>

        {% else %}
        <a id="login" href="{% url 'cooler_math_games:login' %}">&emsp;Login!</a>
        <a id="create_account" href="{% url 'cooler_math_games:signup' %}">&emsp;Create an account!</a>
        {% endif %}
    </div>
    
    <ul id="navlist">
        <a class="navbar-link" href="{% url 'cooler_math_games:Credits' %}"> Credits </a>
        <a class="navbar-link" href="{% url 'cooler_math_games:home' %}"> Games </a>
        <a class="navbar-link" href="{% url 'cooler_math_games:leaderboards' 'current_user' %}"> My High Scores </a>
        <a class="navbar-link" href="{% url 'cooler_math_games:leaderboards' 'all' %}">Leaderboards</a>
    </ul>
</nav>

cooler_math_games/templates/cooler_math_games/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <title>Cooler Math Games Home</title>
    {% load cooler_math_games_extras %}
    {% load static %}
    <link href="{% static 'cooler_math_games/page.css' %}" rel="stylesheet">
    <!-- bootstrap css-->
    
</head>
{% include "./header.html" %}


<body>
    <br>

    <div class="justify-content-center">
        <!--first link/text column-->

        <!--games-->
        <div class="row justify-content-center">
        <div class="col-6" style="margin: auto;
        width: 50%;
        padding: 10px;">

            {% if top_games and game_urls %}
                {% for game, game_link in top_games|zip:game_urls %}
                    <div class="container-c">
                        <div class="image">
                          <img src="{% static 'cooler_math_games/images/'|add:game.name|add:'.png' %}">
                        </div>
                        <div class="text">
                          <a class="title" style="margin-bottom: 5px; " href="{{ game_link }}">{{game.name}}</a>
                          <br>
                          <a>Author: {{game.author}}</a>
                          <br>
                          <a>Total Plays: {{game.total_plays}}</a>
                        </div>
                      </div>
                    <br>
                {% endfor %}
            {% else %}
                <p>Uh oh, there are no games :(</p>
            {% endif %}
        </div>
        </div>

    </div>
    
</body>

</html>

cooler_math_games/templates/cooler_math_games/leaderboards.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Leaderboards</title>
    {% load static %}
    <link href="{% static 'cooler_math_games/leaderboards/leaderboards.css' %}" rel="stylesheet">
  </head>
  <body>
    {% include "./header.html" %}
    <div class="container">
      {% for game, score_data in leader_boards.items %}
      {% if score_data %}
      <h1>Highscores for {{ game }}</h1>
      <table>
        <thead>
          <tr>
            <th>User</th>
            <th>Score</th>
            <th>Date achieved</th>
          </tr>
        </thead>
        <tbody>
          {% for score_information in score_data %}
          <tr>
            <td>{{ score_information.user }}</td>
            <td>{{ score_information.score }}</td>
            <td>{{ score_information.time }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% endif %}
      {% endfor %}
    </div>
  </body>
</html>

cooler_math_games/templates/cooler_math_games/mines.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Mines</title>

        {% load static %}
        <link href="{% static 'cooler_math_games/mines/mines.css' %}" rel="stylesheet">
        <script src ="{% static 'cooler_math_games/mines/mines.js' %}" type="text/javascript"></script>
    </head>

    {% include "./header.html" %}

    <br>

    <body>
        <h1>Mines: <span id="mines-count">0</span> &emsp; Flags Remaining: <span id="flags-remaining">0</span></h1>
        <div id="board">
        </div>
        <br>
        <button id="flag-button">🚩</button>
    </body>
</html>

cooler_math_games/templates/cooler_math_games/phaser_test.html
<!doctype html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8" />
    <title>Making your first Phaser 3 Game - Part 10</title>
    <style type="text/css">

    </style>
    {% load cooler_math_games_extras %}
    {% load static %}
    <link href="{% static 'cooler_math_games/page.css' %}" rel="stylesheet">
    <link href="{% static 'cooler_math_games/phaserTestAssets/phaser_test.css' %}" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/npm/phaser@3.11.0/dist/phaser.js"></script>

</head>

{% include "./header.html" %}
<br>

<body>

<script src="{% static 'cooler_math_games/phaserTestAssets/phaser_test.js' %}" type="text/javascript"></script>
</body>
</html>

cooler_math_games/templates/cooler_math_games/sudoku.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale:1.0, user-scalable=no">
        <title>Sudoku</title>

        {% load static %}
        <link href="{% static 'cooler_math_games/sudoku/sudoku.css' %}" rel="stylesheet">
        <script src ="{% static 'cooler_math_games/sudoku/sudoku.js' %}" type="text/javascript"></script>
    </head>

    {% include "./header.html" %}

    <br>

    <body id="number-page">
        <h1>Sudoku</h1>
        <hr>
        <h2 id="errors">0</h2>
        <!-- 9x9 board -->
        <div id="board"></div>
        <br>
        <div id="digits"></div>
        <br>
        <button onclick="quit_game()" class="button-link">Quit Game</button>
    </body>
</html>

cooler_math_games/templates/cooler_math_games/tomato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tomato Dash!</title>
    {% load static %}
    <link href="{% static 'cooler_math_games/tomato/tomato-dash.css' %}" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/phaser/3.55.2/phaser.min.js"></script>
</head>

{% include "./header.html" %}
<br>

<body>

    <div id="instructions">
        <h2>Instructions</h2>
        <p>
            Grab all the tomatos you and avoid the slime! Use the left, right, and down arrow keys to move and Spacebar to jump! Good luck!
        </p>
    </div>

    <div class="game-container">
        <button id="startButton">Start</button>
        <button id="restartButton" style="display: none;">Restart</button>
    </div>
    <script src="{% static 'cooler_math_games/tomato/tomato-dash.js' %}" type="text/javascript"></script>
</body>

</html>